modules.define('socketio', ['loader_type_js'], function (provide, loader) {

	var host = 'localhost:8081';

	// `socket.io` made with love. we should load autogenerated client library
	// from server. It ensures us to have exactly the same version as on the server
	loader('//' + host + '/socket.io/socket.io.js', function () {
		io.socket = io('http://' + host);
		provide(io);
	});

});
