modules.define('socketio', ['loader_type_js'], function (provide, loader) {

	// `socket.io` made with love. we should load autogenerated client library
	// from server. It ensures us to have exactly the same version as on the server
	loader('//localhost:8081/socket.io/socket.io.js', function () {
		provide(socket = io('http://localhost:8081'));
	});

});
